[project]
name = "positive-password-book"
version = "0.4.1"
license = "AGPL-3.0-only"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["positive-tool~=0.6.0", "typer~=0.20.1", "rich>=14.2.0"]

[project.optional-dependencies]
gui = ["pyside6>=6.10.1"]
build = ["pyinstaller>=6.17.0"]
check = ["mypy>=1.19.1", "ruff>=0.14.14", "ty>=0.0.14"]
feature_encrypt = ["cryptography~=46.0.4"]

[project.urls]
Homepage = "https://github.com/TW0hank0/positive_password_book/"
"Source Code" = "https://github.com/TW0hank0/positive_password_book/"
"Bug Tracker" = "https://github.com/TW0hank0/positive_password_book/issues/"
Changelog = "https://github.com/TW0hank0/positive_password_book/change_log/"
#Documentation = "https://github.com/TW0hank0/positive_password_book/"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
ppb = "ppb.ppb_launcher.launcher:launch"
ppb_tui = "ppb.ppb_launcher.launcher:launch_tui"
ppb_gui = "ppb.ppb_launcher.launcher:launch_gui"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "site-packages",
    "change_log",
    ".logs",
    "assets",
]
line-length = 75
indent-width = 4
